name: CI cache for Dev Environment

on:
  pull_request:
    paths:
      - 'infrastructure/envs/dev/**'

  push:
    paths:
      - '*'

  workflow_dispatch:

jobs:
  dev-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: 0.81.7

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Install Checkov
        run: pip install checkov

      - name: Set plugin cache environment variable
        run: echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >> $GITHUB_ENV

      #- name: Cache Terraform plugin binaries
      #  uses: actions/cache@v4
      #  with:
      #    path: ~/.terraform.d/plugin-cache
      #    key: terraform-plugins-${{ runner.os }}-${{ hashFiles('infrastructure/envs/dev/**/*.[th]f') }}
      #    restore-keys: |
       #     terraform-plugins-${{ runner.os }}-

      - name: Ensure plugin cache directory exists
        run: mkdir -p "$TF_PLUGIN_CACHE_DIR"

      - name: Check Terragrunt HCL formatting
        run: terragrunt hcl format

      - name: Validate Terragrunt configuration
        run: terragrunt hcl validate

      - name: Initialize with Terragrunt (with plugin cache)
        run: |
          TF_PLUGIN_CACHE_DIR="$TF_PLUGIN_CACHE_DIR" terragrunt init \
            --parallelism=40 \
            --terragrunt-working-dir infrastructure/envs/dev \
            --all

      - name: Run Checkov on each Terragrunt module (with plugin cache)
        working-directory: infrastructure/envs/dev
        run: |
          for dir in $(find . -mindepth 1 -maxdepth 1 -type d); do
            echo "ðŸ” Running Checkov for module: $dir"
            cd "$dir"

            TF_PLUGIN_CACHE_DIR="$TF_PLUGIN_CACHE_DIR" terragrunt plan -out=tf.plan
            terragrunt show -json tf.plan > tf.json

            echo "Running checkov inbuilt policies"
            checkov --file tf.json --soft-fail

            echo "Running checkov custom policies"
            if [ -d ../../../../custom_policies ]; then
              checkov --file tf.json --external-checks-dir ../../../../custom_policies --soft-fail
            else
              echo "No custom policies found"
            fi

            cd - > /dev/null
          done

      - name: Run Infracost breakdown
        run: |
          infracost breakdown \
            --path=infrastructure/envs/dev \
            --usage-file=infracost/infracost-usage.yml \
            --format=github-comment \
            --out-file=infracost-dev.json

      - name: Generate Infracost HTML report
        run: |
          infracost output \
            --path=infracost-dev.json \
            --format=html \
            --out-file=infracost-report-dev.html

      - name: Upload Infracost report artifact
        uses: actions/upload-artifact@v4
        with:
          name: infracost-report-dev
          path: infracost-report-dev.html
